### ISSUE TITLE
Empty params in url cause Uncaught SyntaxError

### ISSUE THREAD

**Issue by lostpebble** [solkimicreb/react-easy-params#1]
Hi there,

Just noticed today that this library doesn't seem to play nicely with empty url search query params.

For example, for the url:

```
http://localhost:5000/something?event=
```

I'm getting the following error:

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at toParams (es.es5.js:37)
    at Object.../../node_modules/react-easy-params/dist/es.es5.js (es.es5.js:47)
    at __webpack_require__ (bootstrap:709)
```

I'm actually not even using the params part of this library at the moment, just the storage part - but it seems to run some kind of setup for the params side of things in any case (I assume the backing stores). Looks like its running into some kind of JSON parsing error when a query param is empty in the url.

In this case I believe the params object should look like so:

```
{
   event: "",
}
```

Using the popular `query-string` library, I get an object like that when I parse the query param part of the url.

**Comment by solkimicreb** [comment]
Thanks for the crystal clear issue, it will be an  simple fix.

I would rather have `?event=` result in `params.event === undefined` instead of `params.event === ''`. The reason is that easy-params is preserving type information of query params and 'nothing' pairs best with `undefined` from all the types. Are you okay with this?

**Comment by lostpebble** [comment]
Hmm I'm not too sure, and I've been thinking about this in my use case lately as well. I'm personally leaning towards it being an empty string, because then we can deliberately check on length if we want to deal with it like that in an "undefined" manner. And then it also allows the passing of empty strings deliberately... otherwise how would we deal with that?

Also if `event` was never passed in as a param, then `params.event === undefined` would be true.. which seems truer than if it was deliberately defined in the url.

**Comment by solkimicreb** [comment]
You are right about this. So this is my current proposal in a (url -> object -> url) format

- `?page=12&filter="apple"` -> `{ page: 12, filter: 'apple' }` -> `?page=12&filter="apple"`
- `?page=12&filter=apple` -> `{ page: 12, filter: 'apple' }` -> `?page=12&filter="apple"`
  - invalid type info in url for apple falls back to string
- `?page=12&filter=` -> { page: 12, filter: '' } -> `?page=12`
  - empty query params fall back to empty string, empty object props are not reflected in the url
- `?page=12&filter` -> { page: 12 } -> `?page=12`
  - Totally empty (no = sign) query params are not reflected in the params object.

It might seem a bit complex, but from a practical point this would be the best I think. Having empty strings in the params object is pretty common, since most values come from HTML input values. I would not reflect those in the query to keep things clean.

What is your opinion?

**Comment by lostpebble** [comment]
In my use case, I think I might prefer:

`?page=12&filter= -> { page: 12, filter: '' }-> ?page=12&filter=`

Feel like behaviour should work both ways, as that might be the most expected outcome?

And also because I am using url params to represent inputs on the page which can be set to completely `undefined` (with a checkbox), or they can be deliberately kept empty to represent an empty string.

But that said, I understand where you're coming from too. I guess they're both correct in their own ways.

I'm only noticing now that you're trying to keep type information in the url structure as well- which I'm unsure about because of the established way that url params have worked in the past. I do see the value in it though.

But using that, my preference would then be:

`?page=12&filter= -> { page: 12, filter: '' }-> ?page=12&filter=""`

**Comment by solkimicreb** [comment]
Agreed, functionality is more important than nice query strings. So in the end I have this one implemented:

- `?page=12&filter="apple"` -> `{ page: 12, filter: 'apple' }` -> `?page=12&filter="apple"` -> `{ page: 12, filter: 'apple' }` -> `?page=12&filter="apple"`
- `?page=12&filter=apple` -> `{ page: 12, filter: 'apple' }` -> `?page=12&filter="apple"` ->  `{ page: 12, filter: 'apple' }` -> `?page=12&filter="apple"`
- `?page=12&filter=` -> `{ page: 12, filter: '' }` -> `?page=12&filter=""` -> `{ page: 12, filter: '' }` -> `?page=12&filter=""`
- `?page=12&filter` -> `{ page: 12 }` -> `?page=12` -> `{ page: 12 }` -> `?page=12

Let me know if you agree and I will merge and release it.

Another note: I am pretty sure about including the type info. I know it is a bit unorthodox, but it is really valuable in practice and I see no huge drawbacks because of it.

**Comment by solkimicreb** [comment]
v2.0.2 is out with the changes. Thanks for the tips, I think we found the best solution in the end 🙂
